export interface WFDSentence {
  number: number
  sentence: string
  translation: string
  code: string
  difficulty: string
  labels: string[]
}

export const WFD_SENTENCES: WFDSentence[] = [
  {
    number: 1,
    sentence: 'The celebrated theory is still the source of great controversy.',
    translation: '这一著名的理论至今仍是巨大争议的根源。',
    code: '#131001',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 2,
    sentence: 'A good architectural structure should be useful, durable and beautiful.',
    translation: '一个好的建筑结构应该实用、耐用、美观。',
    code: '#131002',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 3,
    sentence: 'A group meeting will be held tomorrow in the library conference room.',
    translation: '明天将在图书馆会议室举行小组会议。',
    code: '#131003',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 4,
    sentence: 'Educational level is found to be related to social and economic background.',
    translation: '教育水平与社会和经济背景有关。',
    code: '#131005',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 5,
    sentence: 'We can all meet at my office after the lecture.',
    translation: '讲座结束后我们可以在我的办公室见面。',
    code: '#131006',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 6,
    sentence: 'Tutorials are scheduled in the final week of the term.',
    translation: '辅导课安排在学期的最后一周。',
    code: '#131007',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 7,
    sentence: 'You can make an appointment to meet the librarian.',
    translation: '你可以和图书管理员约个时间。',
    code: '#131008',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 8,
    sentence: 'All dissertations must be accompanied by a submission form.',
    translation: '所有论文必须附上提交表格。',
    code: '#131011',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 9,
    sentence: 'All of the assignments must be submitted in person to the faculty office.',
    translation: '所有作业必须亲自提交到学院办公室/教职员工办公室。',
    code: '#131013',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 10,
    sentence: 'Economic development needs to be supported by the government.',
    translation: '经济发展需要政府的支持。',
    code: '#131014',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 11,
    sentence: 'The toughest part of postgraduate education is funding.',
    translation: '研究生教育最困难的部分是资金。',
    code: '#131018',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 12,
    sentence: 'Our view is that educational reforms have been inadequately implemented.',
    translation: '我们的看法是，教育改革执行得不够充分。',
    code: '#131020',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 13,
    sentence: 'An introduction is an essential element of presentation.',
    translation: '简介是演讲的基本要素。',
    code: '#131025',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 14,
    sentence: 'The assignments should be submitted to the department office before the deadlines.',
    translation: '作业须于截止日期前送交系办公室。',
    code: '#131028',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 15,
    sentence: 'Before attending classes, you must register online or by post.',
    translation: '在参加课程之前，你必须在网上或邮寄注册。',
    code: '#131031',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 16,
    sentence: 'Certain scientific principles must be learned verbally or by logical deduction.',
    translation: '某些科学原理必须要通过口头教学或逻辑推理来学习。',
    code: '#131038',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 17,
    sentence: 'Daily practice can build confidence and improve skills.',
    translation: '每天的练习可以建立自信，提高技能。',
    code: '#131048',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 18,
    sentence: 'The economic status of the early Roman Republic will be examined.',
    translation: '我们将考察早期罗马共和国的经济状况。',
    code: '#131053',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 19,
    sentence: 'Human beings compete with other living things for resources and space.',
    translation: '人类与其他生物竞争资源和空间。',
    code: '#131061',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 20,
    sentence: 'Good research delivers practical benefits for real people.',
    translation: '好的研究为人们带来实际的好处。',
    code: '#131064',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 21,
    sentence: 'He landed a job in a very prestigious law firm.',
    translation: '他在一家非常著名的律师事务所找到了一份工作。',
    code: '#131068',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 22,
    sentence: 'The lecture is about the reasons for the financial crisis.',
    translation: '这场讲座是关于金融危机的原因的。 萤 火 之 光 · 点 亮 远 方 第 3 9 1 页 / 共 3 9 9 页',
    code: '#131069',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 23,
    sentence: 'I thought it was through the small meeting room.',
    translation: '我以为是穿过那个小会议室。',
    code: '#131070',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 24,
    sentence: 'If finance is a cause of concern, scholarships may be available.',
    translation: '如果经济原因令人担忧，奖学金也许是可以申请。',
    code: '#131072',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 25,
    sentence: 'If you need additional help, visit the student resource center.',
    translation: '如果你需要额外的帮助，请访问学生资源中心。',
    code: '#131075',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 26,
    sentence: 'Important details from the argument are missing in the summary.',
    translation: '摘要中缺少了论证中的重要细节。',
    code: '#131077',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 27,
    sentence: 'It may not be possible to solve the problem easily.',
    translation: '想要轻易解决这个问题也许是不可能的。',
    code: '#131086',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 28,
    sentence: 'Library reference desks hold a lot of materials on academic history.',
    translation: '图书馆的参考台存放着许多学术史方面的资料。',
    code: '#131091',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 29,
    sentence: 'Listening is the key skill needed to succeed in this course.',
    translation: '听力是学好这门课的关键能力。',
    code: '#131092',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 30,
    sentence: 'Medical researchers have focused on causes of diseases and treatments.',
    translation: '医学研究人员一直致力于研究疾病的病因和治疗方法。',
    code: '#131096',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 31,
    sentence: 'Most of these students have not considered this issue before.',
    translation: '这些学生中大多数人以前都没有考虑过这个问题。',
    code: '#131099',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 32,
    sentence: 'Mutually exclusive events can be described as either complementary or opposite.',
    translation: '互斥事件可以描述为互补的或相反的。',
    code: '#131102',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 33,
    sentence: 'Organizational failure is considered from various perspectives in academic literature.',
    translation: '在学术文献中，人们从不同的角度来思考组织层面的失败。',
    code: '#131111',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 34,
    sentence: 'Plants are the living things that can grow on land or in water.',
    translation: '植物是能在陆地或水中生长的生物。',
    code: '#131119',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 35,
    sentence: 'Public perception about biotechnology is crucial for developing scientific consensus.',
    translation: '公众对生物技术的看法对于形成科学共识至关重要。',
    code: '#131129',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 36,
    sentence: 'Remember, the prestigious election of stewardship has strict eligibility criteria.',
    translation: '记住，这场有声望的管理层选举有严格的资格标准。',
    code: '#131136',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 37,
    sentence: 'Resources and materials are on hold at the library reference desk.',
    translation: '图书馆的咨询台保留着资源和资料。',
    code: '#131137',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 38,
    sentence: 'Many departments have their own special book collections.',
    translation: '许多部门都有自己的特殊藏书',
    code: '#131149',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 39,
    sentence: 'Some economists argue that the entire financial system is fatally flawed.',
    translation: '一些经济学家认为，整个金融体系存在致命的缺陷。',
    code: '#131150',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 40,
    sentence: 'Students have the options to live in college residences or apartments.',
    translation: '学生可以选择住在大学宿舍或公寓。',
    code: '#131159',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 41,
    sentence: 'Students who are successful have good strategies for learning.',
    translation: '成功的学生有很好的学习策略。',
    code: '#131163',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 42,
    sentence: 'The application processes may take longer than expected.',
    translation: '申请过程可能比预期的时间更长。',
    code: '#131175',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 43,
    sentence: 'The archeologists were astonished by the previously overlooked foundations.',
    translation: '考古学家们对以前被忽视的地基感到惊讶。',
    code: '#131176',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 44,
    sentence: 'The cafeteria features soup, salads, sandwiches, chicken and fish.',
    translation: '餐厅主打汤、沙拉、三明治、鸡肉和鱼。',
    code: '#131184',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 45,
    sentence: 'The chemistry building is located near the entrance to the campus.',
    translation: '化学楼位于校园入口处附近。 萤 火 之 光 · 点 亮 远 方 第 3 9 2 页 / 共 3 9 9 页',
    code: '#131186',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 46,
    sentence: 'Rising inflation may indicate an increase in the demand for consumer products.',
    translation: '通货膨胀加剧可能表明对消费品的需求增加。',
    code: '#131196',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 47,
    sentence: 'The faculty staff are very approachable, friendly and extremely helpful.',
    translation: '教职工都很平易近人，友好，而且非常乐于助人。',
    code: '#131205',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 48,
    sentence: 'The history of the university is a long and interesting one.',
    translation: '这所大学的历史悠久而有趣。',
    code: '#131211',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 49,
    sentence: 'The island is located at the south end of the bay.',
    translation: '这个岛位于海湾的南端。',
    code: '#131213',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 50,
    sentence: 'The massive accumulation of data was converted into a communicable argument.',
    translation: '大量的数据积累被转化为一种可用于沟通的论证形式。',
    code: '#131219',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 51,
    sentence: 'The most popular courses still have a few places left.',
    translation: '最受欢迎的课程仍有一些空缺席位。',
    code: '#131222',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 52,
    sentence: 'The qualification will be assessed by using a criterion-referenced approach.',
    translation: '资格将通过使用参考标准进行评估。',
    code: '#131230',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 53,
    sentence: 'The results of the study underscored the importance of early detection.',
    translation: '研究的结果强调了早期发现的重要性。',
    code: '#131235',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 54,
    sentence: 'Safety glasses should be worn while doing experiments in the lab.',
    translation: '在实验室做实验时，应佩戴安全眼镜（护目镜）。',
    code: '#131255',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 55,
    sentence: 'There are some doubts about whether these events actually occurred.',
    translation: '人们对这些事件是否真的发生过有些怀疑。',
    code: '#131262',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 56,
    sentence: 'There is a clear need for further research in this field.',
    translation: '在这个领域明显需要进一步研究。',
    code: '#131263',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 57,
    sentence: 'There is clearly a need for further research in this field.',
    translation: '这一领域显然有进一步研究的必要。',
    code: '#131265',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 58,
    sentence: 'This class will look at the structure of an essay.',
    translation: '这门课将学习一篇文章的结构。',
    code: '#131273',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 59,
    sentence: 'Water filters on campus will discourage the unnecessary use of plastic bottles.',
    translation: '校园里的滤水器可以减少不必要地使用塑料瓶。',
    code: '#131293',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 60,
    sentence: 'We have not yet achieved equality in our society.',
    translation: '我们的社会还没有实现平等。',
    code: '#131297',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 61,
    sentence: 'We study science to understand and appreciate the world around us.',
    translation: '我们学习科学是为了理解和欣赏我们周围的世界。',
    code: '#131298',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 62,
    sentence: 'Parents\' talk to children tends to be simplified.',
    translation: '父母对孩子的谈话往往被简化。',
    code: '#131303',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 63,
    sentence: 'You will acquire many skills during the academic studies.',
    translation: '在学习期间你会学到很多技能。',
    code: '#131316',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 64,
    sentence: 'Speak to your tutor if you need further assistance.',
    translation: '如果你需要进一步的帮助，请和你的导师谈谈。',
    code: '#131330',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 65,
    sentence: 'Education and training provide important skills for the labor force.',
    translation: '教育培训为劳动力提供了重要的技能。',
    code: '#131334',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 66,
    sentence: 'There have been many changes recently in the mathematics department.',
    translation: '最近数学系发生了很多变化。',
    code: '#131352',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 67,
    sentence: 'Those who are considering a career in marketing should attend the talk.',
    translation: '那些正在考虑从事市场营销的人应该参加这次演讲。',
    code: '#131358',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 68,
    sentence: 'The university has invested in new technologies designed to support learning.',
    translation: '大学已投资于新技术，旨在支持学习。 萤 火 之 光 · 点 亮 远 方 第 3 9 3 页 / 共 3 9 9 页',
    code: '#131367',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 69,
    sentence: 'A good academic paper should present a clear argument.',
    translation: '一篇好的学术论文应该呈现一个清晰的论点。',
    code: '#131370',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 70,
    sentence: 'A good research assistant is not afraid to ask questions.',
    translation: '一个好的研究助手不怕问问题。',
    code: '#131371',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 71,
    sentence: 'Collaboration between departments is a feature of successful companies.',
    translation: '部门间的协作是成功公司的一个特点。',
    code: '#131380',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 72,
    sentence: 'Enrolling in a double major may increase your career options.',
    translation: '修双学位可以增加你的职业选择。',
    code: '#131381',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 73,
    sentence: 'Geography is generally divided into two main branches, human and physical.',
    translation: '地理学通常分为两个主要的分支：人文地理和自然地理。',
    code: '#131384',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 74,
    sentence: 'In this language course, we focus on both fluency and accuracy.',
    translation: '在这门语言课程中，我们注重流利度和准确度。',
    code: '#131386',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 75,
    sentence: 'This course provides the opportunity to get valuable industry experience.',
    translation: '本课程提供了可以获得宝贵行业经验的机会。',
    code: '#131393',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 76,
    sentence: 'Read the safety instructions before using any equipment in the workshop.',
    translation: '在使用任何车间设备之前，请先阅读安全说明。',
    code: '#131395',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 77,
    sentence: 'Essays and assignments are spread out across the academic year.',
    translation: '论文和作业分散在整个学年内。',
    code: '#131403',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 78,
    sentence: 'Continuing students will be sent the necessary application forms.',
    translation: '继续就读的学生将收到所需的申请表格。',
    code: '#131405',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 79,
    sentence: 'Calculators may not be used during the examination.',
    translation: '考试期间不得使用计算器。',
    code: '#131407',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 80,
    sentence: 'The elective course introduces engineering students to construction practices and concepts.',
    translation: '选修课程向工程学生介绍了建筑实操和建筑概念。',
    code: '#131409',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 81,
    sentence: 'Our new medical students must attend the talk about optional courses.',
    translation: '我们新来的医学生必须参加关于选修课的讲座。',
    code: '#131414',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 82,
    sentence: 'A professor took one year off to work on her book.',
    translation: '一位教授休了一年的假，专注于撰写她的书籍。',
    code: '#131417',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 83,
    sentence: 'This problem is complex and difficult to explain.',
    translation: '这个问题复杂而难以解释。',
    code: '#131426',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 84,
    sentence: 'Scientists were unsure when the early men first left Africa.',
    translation: '科学家们不能确定早期人类是什么时候第一次离开非洲的。',
    code: '#131462',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 85,
    sentence: 'The printers automatically print on both sides of each page.',
    translation: '打印机自动打印每页的两面。',
    code: '#131471',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 86,
    sentence: 'There is a widely believed perception that engineering is for boys.',
    translation: '人们普遍认为，工程学适合男孩。',
    code: '#131474',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 87,
    sentence: 'Time and distance are used to calculate speed.',
    translation: '时间和距离被用来计算速度。',
    code: '#131479',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 88,
    sentence: 'Distance learning allows you to develop a career around your commitments.',
    translation: '远程学习让你能够围绕已有的事务或安排来发展职业。',
    code: '#131483',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 89,
    sentence: 'Every student has regular meetings with his or her personal tutor.',
    translation: '每个学生与他或她的私人导师定期会面。',
    code: '#131488',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 90,
    sentence: 'Castles were designed to intimidate both local people and enemies.',
    translation: '建造城堡是为了震慑当地人和敌人。',
    code: '#131495',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 91,
    sentence: 'The opening hours of the library are reduced during summer.',
    translation: '图书馆在夏季的开放时间减少了。',
    code: '#131498',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 92,
    sentence: 'A laptop computer has been found in the biology lab.',
    translation: '在生物实验室里发现了一台笔记本电脑。 萤 火 之 光 · 点 亮 远 方 第 3 9 4 页 / 共 3 9 9 页',
    code: '#131499',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 93,
    sentence: 'His appointment as the Minister of Culture was seen as a demotion.',
    translation: '他被任命为文化部长被认为是降职。',
    code: '#131500',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 94,
    sentence: 'Measures must be taken to prevent the unemployment rate from increasing.',
    translation: '必须采取措施防止失业率上升。',
    code: '#131501',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 95,
    sentence: 'Request for late applications will not be accepted under any circumstances.',
    translation: '在任何情况下，都不接受逾期递交的申请。',
    code: '#131509',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 96,
    sentence: 'Salt is produced from seawater or extracted from the ground.',
    translation: '盐是从海水中产生的或从地下提取的。',
    code: '#131513',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 97,
    sentence: 'The news will not be received until the following week.',
    translation: '消息要到下一周才会收到。',
    code: '#131516',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 98,
    sentence: 'You do not need specialist knowledge to enjoy this book.',
    translation: '你不需要专业知识就能欣赏这本书。',
    code: '#131517',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 99,
    sentence: 'The area has a variety of underwater habitats and species.',
    translation: '该地区有各种各样的水下栖息地和物种。',
    code: '#131526',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 100,
    sentence: 'Your ideas are discussed and debated in seminars and tutorials.',
    translation: '你的想法在研讨会和辅导课中被讨论和辩论。',
    code: '#131530',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 101,
    sentence: 'Our study program equips students with essential skills for university.',
    translation: '我们的学习计划使学生具备上大学所需的基本技能。',
    code: '#131532',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 102,
    sentence: 'Many food crops require large amounts of water and fertilizer.',
    translation: '许多粮食作物需要大量的水和肥料。',
    code: '#131535',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 103,
    sentence: 'Classical mechanics is sometimes considered as a branch of applied mathematics.',
    translation: '经典力学有时候被认为是应用数学的一个分支。',
    code: '#131542',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 104,
    sentence: 'Students should leave their bags on the table by the door.',
    translation: '学生们应该把书包放在门边的桌子上。',
    code: '#131544',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 105,
    sentence: 'Sea levels are expected to rise during the next century.',
    translation: '海平面预计在下个世纪会上升。',
    code: '#131556',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 106,
    sentence: 'Please close the door behind you when you leave the room.',
    translation: '离开房间时请随手关门。',
    code: '#131566',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 107,
    sentence: 'The department works closely with business communities.',
    translation: '该部门与商界紧密合作。',
    code: '#131581',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 108,
    sentence: 'There is an accounting assignment for finance students.',
    translation: '金融专业的学生有一个会计作业。',
    code: '#131584',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 109,
    sentence: 'Relying on natural ability will not get you far in science.',
    translation: '在科学/理科的学习上，依靠天生的能力不会使你走得很远。',
    code: '#131585',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 110,
    sentence: 'We should never underestimate the power of creative design.',
    translation: '我们永远不能低估创意设计的力量。',
    code: '#131588',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 111,
    sentence: 'Linguistics is the scientific study and analysis of language.',
    translation: '语言学是针对语言的科学研究和科学分析。',
    code: '#131589',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 112,
    sentence: 'Please return the reference book to the correct position on the library shelf.',
    translation: '请把参考书放回图书馆书架上正确的位置。',
    code: '#131596',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 113,
    sentence: 'Marine environments have been destroyed through pollution and unsustainable development.',
    translation: '由于污染和不可持续的发展，海洋环境遭到破坏。',
    code: '#131603',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 114,
    sentence: 'Designers need to keep up with the social trends.',
    translation: '设计师需要跟上社会潮流。',
    code: '#131604',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 115,
    sentence: 'People have been dependent on using phones in their everyday lives.',
    translation: '人们在日常生活中依赖于使用手机。 萤 火 之 光 · 点 亮 远 方 第 3 9 5 页 / 共 3 9 9 页',
    code: '#131605',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 116,
    sentence: 'A new collection of articles has just been published.',
    translation: '一本新的文集刚刚出版。',
    code: '#131607',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 117,
    sentence: 'A visit to the designed museum is of great value.',
    translation: '参观精心设计的博物馆是非常有价值的。',
    code: '#131609',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 118,
    sentence: 'The university provides excellent leisure facilities for students and staff.',
    translation: '大学为学生和职员提供优质的休闲设施。',
    code: '#131612',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 119,
    sentence: 'Auditions for the university choir will be held next week.',
    translation: '大学合唱团的海选将于下周举行。',
    code: '#131614',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 120,
    sentence: 'A good abstract highlights the key points of your paper.',
    translation: '一篇好的摘要能突出你的论文的重点。',
    code: '#131620',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 121,
    sentence: 'The commissioner will apportion the funds among all the authorities.',
    translation: '专员将把这笔资金分配给所有当局。',
    code: '#131625',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 122,
    sentence: 'Please note that the seminar has now been canceled.',
    translation: '请注意，研讨会现已取消。',
    code: '#131628',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 123,
    sentence: 'Three separate research resources are not enough for this assessment.',
    translation: '对于这份作业来说，三个不同的研究来源是不够的。',
    code: '#131631',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 124,
    sentence: 'Please return your reference books to the library shelves.',
    translation: '请把你的参考书归还到图书馆的书架上。',
    code: '#131632',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 125,
    sentence: 'New media journalism is an exciting area of study.',
    translation: '新媒体新闻是一个令人兴奋的研究领域。',
    code: '#131633',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 126,
    sentence: 'Rising sea temperatures are a sign of climate change.',
    translation: '海水温度上升是气候变化的征兆。',
    code: '#131688',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 127,
    sentence: 'The closing date of applications for travel scholarships is next Monday.',
    translation: '旅游奖学金的申请截止日期是下星期一。',
    code: '#131694',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 128,
    sentence: 'Before preparing food, please make sure to wash your hands.',
    translation: '在准备食物之前，请务必洗手。',
    code: '#131712',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 129,
    sentence: 'The economic predictions turned out to be incorrect.',
    translation: '经济预测结果是不正确的。',
    code: '#131735',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 130,
    sentence: 'Students should take the training course to use the gym.',
    translation: '学生应该参加使用体育馆的培训课程。',
    code: '#131738',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 131,
    sentence: 'The momentum is defined as the combination of mass and velocity.',
    translation: '动量被定义为质量和速度的结合。',
    code: '#131755',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 132,
    sentence: 'More research is needed before any definitive conclusion can be drawn.',
    translation: '在得出任何明确的结论之前，还需要进行更多的研究。',
    code: '#131775',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 133,
    sentence: 'You can get your coffee and tea in the lounge. (不完整，待完善)',
    translation: '您可以在休息室喝咖啡和茶。',
    code: '#131780',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 134,
    sentence: 'In my opinion, the car should be repaired.',
    translation: '在我看来，这辆车应该修理。',
    code: '#131796',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 135,
    sentence: 'The north campus car park could be closed on Sunday.',
    translation: '北校区的停车场可能在周日关闭。',
    code: '#131802',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 136,
    sentence: 'Participating in the class is the center of the course.',
    translation: '课堂参与是课程的核心。',
    code: '#131817',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 137,
    sentence: 'The study center in the library has all the latest technologies.',
    translation: '图书馆的学习中心拥有所有最新的技术。',
    code: '#131827',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 138,
    sentence: 'At university students can make friends for life.',
    translation: '在大学，学生们可以交到一辈子的朋友。',
    code: '#131837',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 139,
    sentence: 'Much of this research is carried out in the laboratory.',
    translation: '这项研究大部分是在实验室里进行的。 萤 火 之 光 · 点 亮 远 方 第 3 9 6 页 / 共 3 9 9 页',
    code: '#131846',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 140,
    sentence: 'Technology is changing the way that media is used and studied.',
    translation: '科技正在改变人们使用和研究媒体的方式。',
    code: '#131851',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 141,
    sentence: 'You will be tested by continuous assessments and examinations.',
    translation: '你将以持续评估和考试的方式接受测试。',
    code: '#131861',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 142,
    sentence: 'The college operates a system of continuous assessments.',
    translation: '这所学院实行持续评估制度。',
    code: '#131864',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 143,
    sentence: 'Scientists have founded all parts of society today.',
    translation: '科学家们建立了当今社会的各个部分。',
    code: '#131866',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 144,
    sentence: 'Novelists write about the best things that they know about.',
    translation: '小说家们写的是他们知⹺的最好的东西。',
    code: '#131878',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 145,
    sentence: 'The lecture today will cover all the main reasons for global warming.',
    translation: '今天的讲座将涵盖全球变暖的所有主要原因。',
    code: '#131904',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 146,
    sentence: 'The rising temperature is changing the wildlife population.',
    translation: '气温上升正在改变野生动物的数量。',
    code: '#131905',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 147,
    sentence: 'The director of the gallery was grateful for the anonymous donation.',
    translation: '美术馆馆长对匿名捐赠表示感谢。',
    code: '#131921',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 148,
    sentence: 'You should have awareness of how the business operates globally.',
    translation: '你应该了解公司是如何在全球范围内运作的。',
    code: '#131923',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 149,
    sentence: 'Art is an expression of creative skills and imagination.',
    translation: '艺术是创造力和想象力的表现。',
    code: '#131924',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 150,
    sentence: 'We have sophisticated ways of studying the brain in action.',
    translation: '我们有复杂成熟的方法来研究大脑的活动。',
    code: '#131928',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 151,
    sentence: 'The article considers the leisure habits of teenagers in rural areas.',
    translation: '本文展现了农村青少年的休闲习惯。',
    code: '#131934',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 152,
    sentence: 'We learned through observations and the analysis of human behaviors.',
    translation: '我们通过观察和分析人类行为来学习。',
    code: '#131946',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 153,
    sentence: 'The subject was complex and difficult to explain.',
    translation: '这个话题/主题/学科很复杂，很难解释。',
    code: '#131952',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 154,
    sentence: 'Our aim is to reduce the risks that people take.',
    translation: '我们的目标是降低人们承担的风险。',
    code: '#131984',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 155,
    sentence: 'Please confirm that you have received the textbook.',
    translation: '请确认课本已经收到。',
    code: '#131987',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 156,
    sentence: 'All answers must be thoroughly researched and supported by relevant theories.',
    translation: '所有答案必须经过充分的研究，并有相关的理论支持。',
    code: '#131992',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 157,
    sentence: 'Accountancy students have to hand in their dissertations this week.',
    translation: '会计专业的学生必须在本周交论文。',
    code: '#131993',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 158,
    sentence: 'His analysis study appears to be based on the false premise.',
    translation: '他的分析研究似乎是基于了错误的前提条件。',
    code: '#1311010',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 159,
    sentence: 'Visual aid can be really helpful when you are revising.',
    translation: '当你复习的时候，视觉辅助真的很有帮助。',
    code: '#1311025',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 160,
    sentence: 'We encourage students to complete their applications before the deadline .',
    translation: '我们鼓励学生在截止日期前完成申请。',
    code: '#1311027',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 161,
    sentence: 'Graduates from this course typically pursue careers in financial sector.',
    translation: '这门课程的毕业生通常会在金融部门工作。',
    code: '#1311047',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 162,
    sentence: 'It is a debate about the value of knowledge.',
    translation: '这是一场关于知识价值的辩论。 萤 火 之 光 · 点 亮 远 方 第 3 9 7 页 / 共 3 9 9 页',
    code: '#1311050',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 163,
    sentence: 'Strangely, people are simultaneously impressed by and skeptical about statistics.',
    translation: '奇怪的是，人们对"统计数据"既感到印象深刻又持怀疑态度。',
    code: '#1311057',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 164,
    sentence: 'The collapse of the housing market has caused recessions.',
    translation: '房地产市场的崩溃引发了经济衰退。',
    code: '#1311066',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 165,
    sentence: 'Calculators allow us to add numbers without making mistakes.',
    translation: '计算器使我们加数字时不犯错误。',
    code: '#1311070',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 166,
    sentence: 'Most of the lectures begin punctually, so do not be late.',
    translation: '大多数的讲座都会准时开始，所以不要迟到。',
    code: '#1311072',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 167,
    sentence: 'The student union hosts a variety of social events.',
    translation: '学生会举办各种各样的社交活动。',
    code: '#1311077',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 168,
    sentence: 'Social psychology is concerned with the understanding of human behaviors.',
    translation: '社会心理学关注的是对人类行为的理解。',
    code: '#1311089',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 169,
    sentence: 'Gravity is the force that attracts two bodies toward one another.',
    translation: '重力是把两个物体相互吸引的力。',
    code: '#1311093',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 170,
    sentence: 'The reception staff can give advice on renting private accommodation.',
    translation: '接待处的工作人员可以提供租用私人住所的建议。',
    code: '#1311098',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 171,
    sentence: 'Artists need to make their works both original and accessible.',
    translation: '艺术家需要使他们的作品既具有原创性又易于理解。',
    code: '#1311102',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 172,
    sentence: 'The archeologist\'s new discoveries stand out in the previously overlooked foundations.',
    translation: '考古学家的新发现在以前被忽视的地基中脱颖而出。',
    code: '#1311195',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 173,
    sentence: 'Please return the textbooks to the correct bookshelves in the library.',
    translation: '请将课本归放到图书馆的正确书架上。',
    code: '#1311203',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 174,
    sentence: 'The contract will be signed by the owner of the company.',
    translation: '这份合同将由公司的所有者签署。',
    code: '#1311204',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 175,
    sentence: 'The glittering of the lake surface camouflages the fish.',
    translation: '湖面的波光使鱼儿难以被发现。',
    code: '#1311205',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 176,
    sentence: 'Having enough sleep has many positive benefits.',
    translation: '充足的睡眠有许多积极的益处。',
    code: '#1311206',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 177,
    sentence: 'Safety is the most important in the biology lab.',
    translation: '在生物实验室中，安全是至关重要的。',
    code: '#1311207',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 178,
    sentence: 'Assessment procedure has been changed slightly since the last year.',
    translation: '与去年相比，评估程序已经做了些许调整。',
    code: '#1311209',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 179,
    sentence: 'The article illustrates the intricate relationship of culture and language.',
    translation: '这篇文章阐述了文化与语言之间错综复杂的关系。',
    code: '#1311210',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 180,
    sentence: 'The tutor has canceled the lecture for geography students.',
    translation: '这位导师已经取消了为地理专业学生安排的课程。',
    code: '#1311213',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 181,
    sentence: 'All accounting students must submit their dissertations before the end of the week.',
    translation: '所有会计专业的学生都必须在本周结束前提交他们的毕业论文。',
    code: '#1311214',
    difficulty: '困难',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 182,
    sentence: 'The next lecture will take place at a different location.',
    translation: '下一场讲座将在另一个地点举行。',
    code: '#1311216',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 183,
    sentence: 'We should always use recycled plastic and glass bottles.',
    translation: '我们应当始终使用可回收的塑料和玻璃瓶。',
    code: '#1311217',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 184,
    sentence: 'Plastic pollution is very dangerous for ocean lives.',
    translation: '塑料污染对海洋生物来说非常有害。',
    code: '#1311218',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 185,
    sentence: 'The content is to define the combination of math and philosophy.',
    translation: '其内容旨在阐述数学与哲学的结合方式。 萤 火 之 光 · 点 亮 远 方 第 3 9 8 页 / 共 3 9 9 页',
    code: '#1311219',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 186,
    sentence: 'Students often conduct research to enhance their knowledge.',
    translation: '学生们经常进行研究以增进自己的知识。',
    code: '#1311224',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 187,
    sentence: 'Farming is affected by changes in seasonal patterns.',
    translation: '农业会受到季节变化的影响。',
    code: '#1311226',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 188,
    sentence: 'The university library cafe is on the third floor.',
    translation: '大学图书馆的咖啡厅在三楼。',
    code: '#1311229',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 189,
    sentence: 'Some students were absent due to the train delay.',
    translation: '一些学生因为火车晚点而未能到场。',
    code: '#1311231',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 190,
    sentence: 'The class is canceled because the professor is sick.',
    translation: '这堂课取消了，因为教授生病了。',
    code: '#1311232',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 191,
    sentence: 'We were discussing the methods used by criminals to commit crimes.',
    translation: '我们当时正在讨论犯罪分子实施犯罪所采用的手段。',
    code: '#1311234',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 192,
    sentence: 'Maths uses numbers and shapes to solve problems.',
    translation: '数学用数字和形状来解决问题。',
    code: '#1311235',
    difficulty: '简单',
    labels: ['极高频'],
  },
  {
    number: 193,
    sentence: 'The employment rate has steadily increased over the last year.',
    translation: '在过去的一年里，就业率持续上升。',
    code: '#1311236',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 194,
    sentence: 'The professor said biology is not the only subject on the exam.',
    translation: '教授说，这次考试的内容并不仅仅局限于生物学这一门科目。',
    code: '#1311237',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 195,
    sentence: 'Participants recorded their sleep hours in the journals.',
    translation: '参与者在日记中记录了自己的睡眠时间。',
    code: '#1311238',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 196,
    sentence: 'Effective communication is the key to becoming a successful manager.',
    translation: '有效的沟通是成为一名成功管理者的关键。',
    code: '#1311239',
    difficulty: '困难',
    labels: ['极高频'],
  },
  {
    number: 197,
    sentence: 'Students need to register to gain access to library printers.',
    translation: '学生需要先注册才能使用图书馆的打印机。',
    code: '#1311240',
    difficulty: '普通',
    labels: ['极高频'],
  },
  {
    number: 198,
    sentence: 'There will be a quiz class next week.',
    translation: '下周将有一次测验课。',
    code: '#1311241',
    difficulty: '简单',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 199,
    sentence: 'Please confirm your essay topic one week before the deadline.',
    translation: '请在截止日期前一周确定您的论文主题。',
    code: '#1311242',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 200,
    sentence: 'The exam will not be posted until further notice.',
    translation: '考试结果要到另行通知时才会公布。',
    code: '#1311244',
    difficulty: '普通',
    labels: ['极高频', '极限预测'],
  },
  {
    number: 201,
    sentence: 'Consumer confidence has a direct influence on sales.',
    translation: '消费者信心对销售有直接影响。',
    code: '#131045',
    difficulty: '简单',
    labels: ['极高频', '重回', '极限预测'],
  },
  {
    number: 202,
    sentence: 'Many universities are continuously expanding the postgraduate education online learning resources.',
    translation: '许多高校都在不断扩大研究生教育的在线学习资源。',
    code: '#131700',
    difficulty: '困难',
    labels: ['极高频', '重回', '极限预测'],
  },
  {
    number: 203,
    sentence: 'The university auditorium is around the corner.',
    translation: '大学礼堂就在转角处。',
    code: '#1311245',
    difficulty: '普通',
    labels: ['极高频', '新题', '极限预测'],
  },
  {
    number: 204,
    sentence: 'The professor discussed the article yesterday in this class.',
    translation: '这位教授昨天在这堂课上讲解了这篇文章。',
    code: '#1311246',
    difficulty: '普通',
    labels: ['极高频', '新题', '极限预测'],
  },
  {
    number: 205,
    sentence: 'Please make sure you have correctly cited all the necessary materials.',
    translation: '请确保你正确引用了所有必要的材料。',
    code: '#131121',
    difficulty: '困难',
    labels: ['降频区'],
  },
  {
    number: 206,
    sentence: 'The coffee machine located on the third floor is not working today.',
    translation: '位于三楼的咖啡机今天不能用了。',
    code: '#131502',
    difficulty: '普通',
    labels: ['降频区'],
  },
  {
    number: 207,
    sentence: 'Teaching assistants play a vital role in the learning process.',
    translation: '教学助理在学习过程中起着至关重要的作用。',
    code: '#131645',
    difficulty: '普通',
    labels: ['降频区'],
  },
  {
    number: 208,
    sentence: 'Summer school programs allow some students to accelerate their studies.',
    translation: '暑期课程允许一些学生加快他们的学习进度。',
    code: '#131743',
    difficulty: '普通',
    labels: ['降频区'],
  },
  {
    number: 209,
    sentence: 'The lecture will cover the reason for climate change.',
    translation: '这场讲座将探讨气候变化的原因。 萤 火 之 光 · 点 亮 远 方 第 3 9 9 页 / 共 3 9 9 页',
    code: '#1311208',
    difficulty: '简单',
    labels: ['降频区'],
  },
  {
    number: 210,
    sentence: 'Application forms should be submitted in one week.',
    translation: '申请表应在一周内提交。',
    code: '#1311225',
    difficulty: '简单',
    labels: ['降频区'],
  },
  {
    number: 211,
    sentence: 'The rise in sea level indicates climate change.',
    translation: '海平面的上升表明了气候在发生变化。',
    code: '#1311228',
    difficulty: '简单',
    labels: ['降频区'],
  },
  {
    number: 212,
    sentence: 'We were talking about ways of committing crimes.',
    translation: '我们当时正在讨论犯罪的作案手法。',
    code: '#1311233',
    difficulty: '普通',
    labels: ['降频区'],
  },
  {
    number: 213,
    sentence: 'We have been unsuccessful in finding a new manager.',
    translation: '我们一直未能找到新的经理人选。',
    code: '#1311243',
    difficulty: '普通',
    labels: ['降频区'],
  },
]
